### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by PhKindermann** [AndreiiArhire/PACE2024#1]
Hey,

I'm having some issues in Step 5 (Setup and Compile the Exact Solver).
I copies the exact_solver.cpp into the exact_solver folder (because it was not there, of course): `cp ../../../exact.cpp .`
But now when running the compile command, I get the following error:
```bash
$ g++ -o exact exact.cpp -I../../src -I../../build -L../../build/lib -lhighs -static
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `std::unique_ptr<zstr::detail::z_stream_wrapper, std::default_delete<zstr::detail::z_stream_wrapper> >::~unique_ptr()':
HMpsFF.cpp:(.text._ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev[_ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev]+0x19): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev[_ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev]+0x23): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::~istreambuf()':
HMpsFF.cpp:(.text._ZN4zstr10istreambufD2Ev[_ZN4zstr10istreambufD2Ev]+0x29): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambufD2Ev[_ZN4zstr10istreambufD2Ev]+0x33): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::~istreambuf()':
HMpsFF.cpp:(.text._ZN4zstr10istreambufD0Ev[_ZN4zstr10istreambufD0Ev]+0x29): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambufD0Ev[_ZN4zstr10istreambufD0Ev]+0x33): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::underflow()':
HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x173): undefined reference to `inflateInit2_'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x198): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x1a2): undefined reference to `deflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x1dc): undefined reference to `inflate'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x221): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x22b): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
```

Do you have any idea what's going wrong?

**Comment by AndreiiArhire** [comment]
Hello! 
Thank you for reaching out. I think the error you're encountering is related to missing zlib symbols when linking.A feasible solution could be to run the make sure the files are installed with "sudo apt install zlib1g-dev" and update the compile command to include the zlib library by adding -lz: "g++ -o exact exact.cpp -I../../src -I../../build -L../../build/lib -lhighs -lz -static".
Most likely a possible explanation is that there are environment differences or pre-existing conflicts.I created a new Oracle Virtual Machine with Ubuntu 20.04 LTS to test the setup and compile the exact solver (and heuristic), and it worked smoothly with the steps provided.If you’re still facing issues, please let me know. I hope everything is fine with the evaluation of the heuristic solver.
Best regards,
Andrei

    On Monday, June 17, 2024 at 05:47:52 PM GMT+3, PhKindermann ***@***.***> wrote:  
 
 


Hey,

I'm having some issues in Step 5 (Setup and Compile the Exact Solver).
I copies the exact_solver.cpp into the exact_solver folder (because it was not there, of course): cp ../../../exact.cpp .
But now when running the compile command, I get the following error:
$ g++ -o exact exact.cpp -I../../src -I../../build -L../../build/lib -lhighs -static
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `std::unique_ptr<zstr::detail::z_stream_wrapper, std::default_delete<zstr::detail::z_stream_wrapper> >::~unique_ptr()':
HMpsFF.cpp:(.text._ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev[_ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev]+0x19): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev[_ZNSt10unique_ptrIN4zstr6detail16z_stream_wrapperESt14default_deleteIS2_EED2Ev]+0x23): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::~istreambuf()':
HMpsFF.cpp:(.text._ZN4zstr10istreambufD2Ev[_ZN4zstr10istreambufD2Ev]+0x29): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambufD2Ev[_ZN4zstr10istreambufD2Ev]+0x33): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::~istreambuf()':
HMpsFF.cpp:(.text._ZN4zstr10istreambufD0Ev[_ZN4zstr10istreambufD0Ev]+0x29): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambufD0Ev[_ZN4zstr10istreambufD0Ev]+0x33): undefined reference to `deflateEnd'
/usr/bin/ld: ../../build/lib/libhighs.a(HMpsFF.cpp.o): in function `zstr::istreambuf::underflow()':
HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x173): undefined reference to `inflateInit2_'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x198): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x1a2): undefined reference to `deflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x1dc): undefined reference to `inflate'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x221): undefined reference to `inflateEnd'
/usr/bin/ld: HMpsFF.cpp:(.text._ZN4zstr10istreambuf9underflowEv[_ZN4zstr10istreambuf9underflowEv]+0x22b): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
Do you have any idea what's going wrong?

**Comment by PhKindermann** [comment]
Adding -`lz` to the compile command worked, thanks!
